const dictionaries = {

'per' : ["ÇãíÑÍÓíä ÚÈÇÓí ÔÇå˜æå | ÑÒæãå",
	"ÇãíÑÍÓíä ÚÈÇÓí ÔÇå˜æå",
	"Òíäå åÇ",
	"ÑÒæãå",
	"ÇØáÇÚÇÊ ÔÎÕí",
	"ãåÇÑÊ åÇí ÈÑäÇãå äæíÓí",
	"ãåÇÑÊ åÇí ÒÈÇäí",
	"Ñæå åÇ æ ˜ÇÑåÇí ÊÍŞíŞÇÊí",
	"ÑÔÊå",
	"ãÏÑ˜",
	"ÓÇá ÇÎĞ ãÏÑ˜",
	alphabet[1],
	"ÏÈíÑÓÊÇä ˜ãÇá",
	"ÑíÇÖí İíÒí˜",
	"Ïíáã",
	alphabet[1]+alphabet[3]+alphabet[9]+alphabet[5],
	alphabet[2],
	"ÏÇäÔÇå Úáã æ ÕäÚÊ ÇíÑÇä",
	"ãåäÏÓí ˜ÇãíæÊÑ",
	"˜ÇÑÔäÇÓí",
	alphabet[1]+alphabet[4]+alphabet[0]+alphabet[1],  
	"ÑÊÈå ÏÑ ˜ä˜æÑ ÓÑÇÓÑí æÑæÏ Èå ÏÇäÔÇå åÇ ÓÇá"+alphabet[1]+alphabet[3]+alphabet[9]+alphabet[6],
	"ãÓÆæáíÊ ĞíÑí æ ãÔÇÑ˜Ê ÏÑ Ñæå",
	"ÊÌÑÈå åã˜ÇÑí Êíãí ÈÑÇí íÔ ÈÑÏ äÑã ÇİÒÇÑ ÏÑ ŞÇáÈ ÑæÔ åÇí ÇÈ˜ (Scrum)",
	"ãÌãæÚå í ãÇí˜ÑæÓÇİÊ ÂİíÓ (ÏÑ ÍÏ ÎæÈ)",
	"ÂÏæÈ İæÊæÔÇ (ÎæÈ)",
	"ÑæÔ åÇí Èåíäå í ÌÓÊÌæ æ ÊÍŞíŞ ÏÑ ÇíäÊÑäÊ æ ÇÓÊİÇÏå ÇÒ ãæÊæÑåÇí ÌÓÊÌæ",
	"ÊÍáíá äÍæí æ áÛæí ÈÇ ÇÓÊİÇÏå ÇÒ ÇÈÒÇÑ ANTLR ÈÑÇí ÇíÊæä",
	"ØÑÇÍí í˜ ÒÈÇä ÎÇÕ ãäÙæÑå ÈÇ ÇÓÊİÇÏå ÇÒ ÇÈÒÇÑ ANTLR ÈÑÇí ØÑÇÍí ÕİÍå æ GUI",
	"ÂÒãæä äÑã ÇİÒÇÑ ÈÇ ÇÓÊİÇÏå ÇÒ ÇÈÒÇÑ Behave æ ÑæÔ åÇí BDD",
	"ÂÔäÇíí ÈÇ ÔÈíå ÓÇÒí ÔÈ˜å ÈÇ ÇÓÊİÇÏå ÇÒ ÇÈÒÇÑ Cisco Packet Tracer",
	"˜ãí ÊÌÑÈå í Web Scrapping ÈÇ ÇÓÊİÇÏå ÇÒ ÇíÊæä",
	"˜äÊÑá ÔÈ˜å ÈÑÇÓÇÓ ÑæÊ˜á SNMP æ ˜ÊÇÈÎÇäå í net-snmp",
	"ÈÑäÇãå äæíÓí AVR ATMEGA32 (ÊÌÑÈå í ˜ã)",
	"ØÑÇÍí æ íÇÏå ÓÇÒí ãÏÇÑåÇí ãäØŞí ÏÑ Ñæå æÇŞÚí",
	"ÔÈíå ÓÇÒí ãÏÇÑ ãäØŞí ÈÇ ÇÓÊİÇÏå ÇÒ ModelSim æ Proteus (ÎæÈ)",
	"ÊÌÑÈå ˜Çİí ÏÑ ÈÑäÇãå äæíÓí VHDL æ Verilog ÈÑÇí ØÑÇÍí ÓíÓÊã åÇí ÏíÌíÊÇá",
	"ÂÔäÇíí ÈÇ Raspberry æ Arduino",
	"ÊÌÑÈå ÎæÈ ÏÑ ÈÑäÇãå äæíÓí SQL(SQlite) æ ÇÓÊİÇÏå ÇÒ ÇÈÒÇÑ Microsoft SQL Server",
	"ÂÔäÇíí ÈÇ ÑæÔ åÇí ÊÍáíá ÏÇÏå",
	"ÊÌÑÈå ÎæÈ ÏÑ ØÑÇÍí ÔÈ˜å åÇí ÎæÏíÇÏíÑ æ íÇÏíÑí ãÇÔíä (ÈÇ ÇÓÊİÇÏå ÇÒ ˜ÊÇÈÎÇäå åÇí Numpy æ Tensorflow ÏÑ ÇíÊæä)",
	"ÍÑİå Çí ÏÑ ÈÑäÇãå äæíÓí ÏÓÊæÑÇÊ áíäæ˜Ó",
	"ÊÌÑÈå ÎæÈ ÏÑ ÇÓÊİÇÏå ÇÒ İÑÇÎæÇäí ÓíÓÊã áíäæ˜Ó",
	"ÊÍÕíáÇÊ",
	"Úáæã ÏÇÏå",
	"åæÔ ãÕäæÚí",
	"ÓíÓÊã ÚÇãá",
	"ÓÎÊ ÇİÒÇÑ æ ØÑÇÍí ãÏÇÑ",
	"ãåÇÑÊ åÇí ÔÈ˜å",
	"ÂÒãæä äÑã ÇİÒÇÑ",
	"˜ÇãÇíáÑ æ ÊÍáíá ÒÈÇäí",
	"ãåÇÑÊ åÇí Úãæãí",
	"äÇã",
	"ÇãíÑÍÓíä",
	"äÇã ÎÇäæÇÏí",
	"ÚÈÇÓí ÔÇå˜æå",
	"ÊÇÑíÎ ÊæáÏ",
	alphabet[2]+" ÂĞÑ "+alphabet[1]+alphabet[3]+alphabet[7]+alphabet[7],
	"ÂÏÑÓ Çíãíá",
	"ÔãÇÑå",
	"ãÍá",
	"ãÈÊÏí",
	"ãÊæÓØ",
	"íÔÑİÊå",
	"ÎÈÑå",
	"ÇíÊæä",
	"ÌÇæÇ",
	"ÇÈÊÏÇíí",
	"ãÍÏæÏ",
	"ÍÑİå Çí",
	"ÒÈÇä ãÇÏÑí",
	"İÇÑÓí",
	"ÇäáíÓí",
	"ÚÑÈí",
	"++C #C",
	alphabet[9]+alphabet[8]+alphabet[4],
	"ãæÖæÚÇÊ",
	"ØÑÇÍí í˜ ÒÈÇä ÎÇÕ ãäÙæÑå ÈÇ ÇÓÊİÇÏå ÇÒ ÇÈÒÇÑ ANTLR ÈÑÇí ØÑÇÍí ÕİÍå æ GUI",
	"ÇãíÑÍÓíä ÚÈÇÓí ÔÇå˜æå",
	"ÈÑäÇãå äæíÓí æÈ/Çáí˜íÔä",
	"Ñæå åÇ æ ˜ÇÑåÇí ÊÍŞíŞÇÊí",
	],

'ar':   ["ÃãíÑÍÓíöä ÚóÈøÇÓí ÔÇå˜æå | ÓíÑÉ ÇáĞÇÊíÉ",
	"ÃãíÑÍÓíöä ÚóÈøÇÓí ÔÇå˜æå",
	"ÎíÇÑÇÊ",
	"ÓíÑÉ ÇáĞÇÊíÉ",
	"ãÚáæãÇÊ ÔÎÕíÉ",
	"ãåÇÑÇÊ ÇáÈÑãÌÉ",
	"ãåÇÑÇÊ ÇááÛæíÉ",
	"ãÔÇÑíÚ æÇáÈÍæË",
	"ãÌÇá",
	"ÏÑÌÉ",
	"ÓäÉ ÇáÊÎÑÌ",
	alphabet[1],
	"ãÏÑÓÉ ßãÇá ÇáËÇäæíÉ¡ ØåÑÇä",
	"ÃáÑøíÇÖíÇÊ",
	"ÏÈáæã",
	alphabet[2]+alphabet[0]+alphabet[1]+alphabet[7],
	"2",
	"ÌÇãÚÉ ÅíÑÇä ááÚáæã æÇáÊŞäíÉ (IUST)",
	"åäÏÓÉ ÇáßãÈíæÊÑ",
	"ÈßÇáæÑíæÓ",
	alphabet[2]+alphabet[0]+alphabet[2]+alphabet[2],
	"ãÑÊÈÉ İí ÇáÇáÊÍÇŞ ÈÇáÌÇãÚÉ ÇáæØäíÉ (ÓäÉ "+alphabet[2]+alphabet[0]+alphabet[1]+alphabet[7]+")",
	"ÇáãÓÄæáíÉ æÇáÊÚÇæä İí ÇáİÑíŞ",
	"İÑíŞ ÇáÚãá ÈÇÓÊÎÏÇã ÇáÃÓÇáíÈ ÇáÑÔíŞÉ áÊäİíĞ ÇáÈÑÇãÌ İí ÇáãÔÑæÚ (ØÑíŞÉ SCRUM)",
	"ãÌãæÚÉ ãÇíßÑæÓæİÊ ÃæİíÓ",
	"ÂÏæÈ İæÊæÔÇ",
	"ÇÓÊÎÏÇã ØÑŞ ÇáÈÍË ÇáİÚÇáÉ æÇáÈÍË ÈÇÓÊÎÏÇã ÇáÃÏæÇÊ æÎÏãÇÊ ÇáÈÍË ÚÈÑ ÇáÅäÊÑäÊ",
	"ÇáÊÍáíá ÇááÛæí æÇáäÍæí ÈÇÓÊÎÏÇã ÃÏæÇÊ ANTLR áÈÇíËæä",
	"Õãã áÛÉ ãÚíäÉ (DSL) ÈÇÓÊÎÏÇã ÃÏæÇÊ ANTLR áÊÕãíã ÇáæÇÌåÉ ÇáÑÓæãíÉ",
	"İÍÕ ÈÑÇãÌ BDD áäÕæÕ Python (ÈÇÓÊÎÏÇã Behave)",
	"Úáí ãØáÚ ãÍÇßÇÉ ÇáÔÈßÉ ÈÇÓÊÎÏÇã ÈÑäÇãÌ Cisco Packet Tracer",
	"ÎÈÑÉ ŞáíáÉ İí ÊÌÑíİ ÇáæíÈ(Web Scraping) æÊÍáíá ÕİÍÇÊ ÇáæíÈ ÈÇÓÊÎÏÇã ÈíËæä",
	"ãÑÇŞÈÉ ÇáÔÈßÉ Úáì ÃÓÇÓ ÈÑæÊæßæá SNMP ÈÇÓÊÎÏÇã ãßÊÈÉ net-snmp",
	"ÎÈÑÉ ŞáíáÉ İí ÈÑãÌÉ AVR ATMEGA32",
	"ÊÕãíã æÊäİíĞ ÇáÏæÇÆÑ ÇáãäØŞíÉ İí ãÔÑæÚ ÍŞíŞí",
	"ÎÈÑÉ ßÇİíÉ İí ãÍÇßÇÉ ÇáÊÕãíã ÇáãäØŞí ÈÇÓÊÎÏÇã ModelSim æ Proteus",
	"ÎÈÑÉ ßÇİíÉ İí ÈÑãÌÉ VHDL æ Verilog æÃäÙãÉ ÇáÊÕãíã ÇáÑŞãí",
	"Úáí ãØáÚ Raspberry æ Arduino",
	"ÎÈÑÉ ßÇİíÉ İí Microsoft SQL Server æÈÑãÌÉ SQL ÇáÇÍÊÑÇİíÉ (SQlite)",
	"Úáí ãØáÚ ØÑŞ ÊÍáíá ÇáÈíÇäÇÊ",
	"ÊÚáã ÇáÂáÉ æÊÕãíã äãÇĞÌ ÔÈßÉ ÇáÊÚáã ÇáĞÇÊí (ÈÇÓÊÎÏÇã Numpy æ TensorFlow İí áÛÉ ÈíËæä)",
	"ÇáÈÑãÌÉ ÇáÇÍÊÑÇİíÉ áÃæÇãÑ ÓØÑ ÃæÇãÑ Linux æ Bash",
	"ÎÈÑÉ ßÇİíÉ İí ÇÓÊÎÏÇã ÇÓÊÏÚÇÁ ÇáäÙÇã Linux",
	"ÊÚáíãÇÊ",
	"Úáæã ÇáÈíÇäÇÊ",
	"ÇáĞßÇÁ ÇáÇÕØäÇÚí",
	"äÙÇã ÇáÊÔÛíá",
	"ÚÊÇÏíÇÊ æ ÊÕãíã ÇáÏæÇÆÑ",
	"ãåÇÑÇÊ ÇáÔÈßÉ",
	"İÍÕ ÇáÈÑãÌíÇÊ",
	"ãõÊÑÌöã æ ÇáÊÍáíá ÇááÛæí",
	"ãåÇÑÇÊ ÚÇãÉ",
	"ÇáÇÓã ÇáÃæá",
	"ÇãíÑÍÓíä",
	"ÇÓã ÇáÚÇÆáÉ",
	"ÚÈÇÓí ÔÇå˜æå",
	"ÊÇÑíÎ ÇáãíáÇÏ",
	alphabet[3]+" ÔÚÈÇä "+alphabet[1]+alphabet[4]+alphabet[1]+alphabet[9]+" ("+""+alphabet[2]+alphabet[3]+" äæİãÈÑ "+alphabet[1]+alphabet[9]+alphabet[9]+alphabet[8]+" ãíáÇÏíÉ"+")",
	"ÚäæÇä ÇáÈÑíÏ ÇáÅáßÊÑæäí",
	"ÑŞã",
	"ã˜Çä",
	"ÇÈÊÏÇÆí",
	"ãÊæÓØ",
	"ãÊŞÏã",
	"ÎÈíÑ",
	"ÈíËæä",
	"java",
	"ÇÈÊÏÇÆí",
	"ãÍÏæÏ",
	"ãÍÊÑİ",
	"ãÍáí",
	"ÇáİÇÑÓíÉ",
	"ÅäÌáíÒí",
	"ÇáÚÑÈíÉ",
	"++C #C",
	alphabet[9]+alphabet[8]+alphabet[4],
	"ãÌÇáÇÊ",
	"Õãã áÛÉ ãÚíäÉ (DSL) ÈÇÓÊÎÏÇã ÃÏæÇÊ ANTLR áÊÕãíã ÇáæÇÌåÉ ÇáÑÓæãíÉ",
	"ÃãíÑÍÓíä ÚÈÇÓí ÔÇå˜æå",
	"ÈÑãÌÉ æíÈ/ÊØÈíŞíÉ",
	"ãÔÇÑíÚ æÇáÈÍæË",
	],
'eng' : ["CV | Amirhossein Abbasi", "Amirhossein Abbasi Shahkooh", "Menu", "CV", "Personal Information", "Programming Skills", "Languages Skills","Projects & researches",
	'Field', 'Degree', 'Graduation year', '1', 'Kamal High School, Tehran', 'Mathematics', 'Diploma', '2017', '2',
	 'Iran university of science and technology (IUST)', 'Computer Engineering', 'BSc', '2022', 'rank in Iran national university entrance exam',
	 'Responsibility and cooperation in team', 'Team working by using agile methods to implement software in project (Scrum method)',
	 'Microsoft office softwares and tools (good)', 'Adobe photoshop (good)',
	 'Efficient research methods and search by using online tools and search services', 'Syntax and lexical analysis by using ANTLR tools for Python ',
	 'Design a DSL by using ANTLR tools', 'BDD Software testing for python program (using Behave)',
	 'familiar with Network simulation with Cisco Packet Tracer software', 'A little experience  in Web Scrapping and parsing web pages using python',
	 'Network monitoring based on SNMP protocol using net-snmp library', 'AVR ATMEGA32 programming',
	 'Design and implementation of logic circuit in a real project', 'Logic design simulating by ModelSim and Proteus (good)',
	 'VHDL and Verilog programming (Good) and design digital systems', 'Familiar with Raspberry and Arduino',
	 'Microsoft SQL Server (good) and professional SQL programming (SQlite)', 'Familiar with data analysis methods',
	 'Machine Learning and design self-learning network models (using Numpy and TensorFlow)', 'Linux command script (Professional)',
	 'Linux system calls (Good)','Education', 'Data Science', 'Artificial Intelligence', 'Operating Systems', 'Hardware (Circuit Design)',
	 'Network skills', 'Software Test', 'Compiler and linguistic analysis', 'General Skills', 'First Name', 'Amir Hossein', 'Last Name',
	 'Abbasi Shahkooh', 'Birth date', '23 Nov 1998', 'Email Address', 'No', 'School',
	'Beginner', 'Intermediate', 'Advanced', 'Expert', 'Python', 'Java', 'Elementary', 'Limited', 'Professional',
        'Native', 'Persian', 'English', 'Arabic','C# C++','984','Fields','Design a DSL by using ANTLR tools  ',"Amirhossein Abbasi Shahkooh ","Web/App Programming",],
};
const lang_dir = {
'per' : "rtl",
'eng' : "ltr",
'ar' : "rtl",
};